OPENAI_API_KEY = "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"
OPENAI_PROJECT_ID = "proj_qRQpbaVORYLCHk3QwTzPoPHW"

