OPENAI_API_KEY = "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"
OPENAI_PROJECT_ID = "proj_qRQpbaVORYLCHk3QwTzPoPHW"

